travis:
  secure:
    BINSTAR_TOKEN: ohh9TSRwxSLukRV2tJvEqY9ZGvL/FsyYdXcNRRJajNMCOpOcm2A+/1GNTg2iIVCmxZ/KkQ1+dhX6uR3JvSE0ItbfgkZ16xnZxGd0TmykH+MctVVkExjgTClTrtEhRFP7PyPm/bkPGAHm2e3zLPncMX/msmG/jNqzgHfbkN+WE1m20fPuR0Xt/q0W7h76Yg5HIZoepdqO3Dz2wsdLtcSlKbGM3K4lZ9no/7GaoYSfFFwuzNb0oUGge3zywghMisSRXDPa8+3v943ptdMwlrzTsl+lvVAimJjfiy8TRWkDWczzqRNIM60uKZ+taaUI0BGvj0bdjMypqCTJi/S7hFb3CcY+j6bDQmxL2g3mX+k6dFDV9VIotsVEx9RZ4tHRqlk6R59tom75+nD8FKTwj2vkYonv5p63f8ssmYnOq5VSkBYeJYrk4vbP92cmZrj8Bs3jRmuymZ8kF0xNP5FyLysbJE8Qiw/NDDdY+umcva4oWYFaVXh2EER7Ek8erLbApzBVQNgPFGdj3NTUEdtg7Zf5qkVsHUjxHa9Z2t/5AZW6araDKYvGF67tKDgnPmL+iVxDVjkQ0xywhlEa7GhvhM+9oswaJu+XEmepqD4vYNAEaaP0iD5jTC3oDocf7kwd/n1nEw8H9Xkh9ZdklGksv972WA7y4xpdmsIWOmg90cy3gCg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
